### ISSUE TITLE
Suggested Docs Edit to point to V2 dbgp.ahk lib

### ISSUE THREAD

**Issue by hasteagag** [Lexikos/DebugVars.ahk#4]
although users may find their way to the v2 repo, suggest updating the readme link regarding the include to https://github.com/Lexikos/dbgp/tree/two

**Comment by Lexikos** [comment]
The readme has been updated by #5.

I don't intend to support AutoHotkey v1 or any of my v1 scripts, so have also changed the default branch for dbgp to `two`.
